---
title: "COVID-19 Vaccine Perception and Distribution"
author: "Jenn Schilling"
date: "3/13/2021"
output: html_document
---

```{r setup, include=FALSE}

# Packages
library(tidyverse)
library(extrafont)
library(wesanderson)
library(ggalluvial)
library(ggtext)
library(patchwork)

# Plot Formatting
font <- "Gill Sans MT"
fontcolor <- "gray30"

theme_set(theme_minimal(base_size = 12, base_family = font))

theme_update(
  
  text = element_text(size = 10, color = fontcolor), 
  
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  
  axis.text = element_text(size = 10, color = fontcolor),
  
  legend.title = element_text(size = 12, color = fontcolor),
  legend.text = element_text(size = 10, color = fontcolor),
  
  plot.title.position = "plot",
  plot.title = element_text(size = 12, face = "bold"),
  
  plot.subtitle = element_text(size = 10, color = fontcolor),
  
  plot.caption.position = "plot",
  plot.caption = element_markdown(size = 8, color = fontcolor, hjust = 0),
  
  plot.margin = margin(t = 25, r = 25, b = 10, l = 25),
  
  plot.background = element_rect(fill = "#fafafa", color = NA)
)

# Data

dat <- tibble(
  race = c("White", "Black", "Hispanic/Latino"),
  
  # Source: http://maristpoll.marist.edu/wp-content/uploads/2021/03/NPR_PBS-NewsHour_Marist-Poll_USA-NOS-and-Tables_202103091124.pdf#page=25
  # Question: If a vaccine for the coronavirus is made available to you, will you choose to be vaccinated or not? If you have already received the vaccine, please say so.
  
  # Response: Yes, will
  want_vacc_poll = c(0.43, 0.48, 0.52),
  
  # Response: Yes, already received
  have_vacc_poll = c(0.27, 0.25, 0.11),
  
  # Source: https://covid.cdc.gov/covid-data-tracker/#vaccination-demographic
  
  # Race/Ethnicity of People Fully Vaccinated (3/12/21)
  # Data from 35,000,159 people fully vaccinated. Race/Ethnicity was available for 18,721,472 (53.5%) people fully vaccinated.
  full_vacc = c(0.684, 0.066, 0.073),
  
  # Race/Ethnicity of People with at least One Dose Administered (3/12/21)
  # Data from 65,965,305 people with at least one dose administered. Race/Ethnicity was available for 35,139,015 (53.3%) people with at least one dose administered.
  partial_vacc = c(0.66, 0.073, 0.085),
  
  # Source: https://www.census.gov/quickfacts/fact/table/US/PST045219#qf-headnote-b
  # Population estimates, July 1, 2019
  us_pop = c(0.601, 0.134, 0.185)
  
)

```


```{r poll-plot}

poll_plot <-
ggplot(data = dat,
       mapping = aes(label = scales::percent(want_vacc_poll + have_vacc_poll,
                                             accuracy = 1),
                     x = race,
                     y = c(0, 0, 0),
                     color = race)) +
  geom_text(family = font,
            size = 8,
            hjust = 0.5,
            position = position_nudge(y = 0.2)) +
  geom_text(mapping = aes(label = race,
                          y = c(-0.15, -0.15, -0.15)),
            color = fontcolor,
            family = font,
            size = 5,
            hjust = 0.55,
            position = position_nudge(y = 0.2)) +
  scale_color_brewer(palette = "Dark2") +
  scale_y_continuous(limits = c(-0.2, 0.3)) +
  coord_cartesian(clip = "off") +
  guides(color = FALSE) +
  labs(title = "Percent of people who plan to get the vaccine or have already done so",
       subtitle = "Based on data from an NPR/PBS NewsHour/Marist Poll of 1,227 National Adults; 3/3/21 - 3/8/21",
       x = "",
       y = "") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        plot.margin = margin(t = 25, r = 25, b = 0, l = 25))

```


```{r vacc-plot}

dat_long <-  dat %>% 
  select(race, full_vacc, partial_vacc, us_pop) %>%
  pivot_longer(full_vacc:us_pop,
               names_to = "axis",
               values_to = "pct") %>%
  mutate(axis = factor(axis, levels = c("us_pop", "partial_vacc", "full_vacc")))

dat_long_labels <- tibble(
  x = c(0.92, 0.92, 0.92),
  y = c(0.855, 0.7, 0.305),
  race = c("Black", "Hispanic/Latino", "White"),
  label = c("Black", "Hispanic/\nLatino", "White")
)

vacc_plot <- 
ggplot(data = dat_long,
       mapping = aes(y = pct,
                     x = axis,
                     stratum = race,
                     alluvium = race,
                     fill = race,
                     label = scales::percent(pct, accuracy = 0.1))) +
  geom_alluvium(width = 1/8) +
  geom_stratum(width = 1/8,
               alpha = 0.5,
               color = NA) +
  geom_text(stat = "stratum",
            family = font,
            color = "gray10",
            size = 3.5) +
  geom_text(data = dat_long_labels,
            mapping = aes(x = x,
                          y = y,
                          label = label),
            family = font,
            color = fontcolor, 
            size = 4.5,
            hjust = 1) +
  scale_fill_brewer(palette = "Dark2") +
  scale_x_discrete(labels = c("% of U.S.\nPopulation",
                              "% of Partially and Fully\nVaccinated People",
                              "% of Fully\nVaccinated People")) +
  guides(fill = FALSE) +
  coord_cartesian(expand = FALSE,
                  clip = "off") +
  labs(title = "Distribution of vaccinations by race/ethnicity compared to the U.S. population",
       caption = "Partially vaccinated people have received one of two doses.<br>**Data:** U.S. Census Bureau, Population Estimates 7/1/2019 | CDC, Overall US COVID-19 Vaccine Distribution and Administration 3/12/2021",
       x = "",
       y = "") +
  theme(axis.text.x = element_text(size = 11),
        axis.text.y = element_blank(),
        plot.caption = element_markdown(hjust = 0),
        plot.margin = margin(t = 0, r = 25, b = 10, l = 25))

```


```{r combine-plots}

combined_plot <- 
  poll_plot / vacc_plot + 
  plot_layout(ncol = 1,
              heights = c(1, 5)) +
  plot_annotation(title = "Similar proportions of people want the coronavirus\nvaccine but distribution has not been equitable",
                  caption = "**Design:** Jenn Schilling",
                  theme = theme(plot.caption = element_markdown(hjust = 1.1),
                                plot.title = element_text(size = 18)))

ggsave("covid_vaccine_plot.png",
       plot = combined_plot,
       device = "png",
       width = 8,
       height = 10,
       type = "cairo")

```

